### ISSUE TITLE
能删除node发送相关代码么？

### ISSUE THREAD

**Issue by nimoc** [100apps/IWantYou#5]
可以理解这个项目是一个非许可式邮件群发器。

具体发送代码不重要，重要的是人人都知道可以用 github 提供的API给所有在上海的Web前端发非许可方邮件会是一件很恶心的事。

而且，我只在github留自己的邮箱，其他任何平台的邮箱都是专门用于注册账号的邮箱。就是为了**避免邮箱中都是招聘和广告邮件**。此项目浏览的人越多，github 用户邮箱中的广告邮件就越多。

**Comment by xuexb** [comment]
@nimojs 然而古代流传下来有个叫**黑色单**啊，然而，你太出名了，偶邮箱3.54年没见过邮件了～

**Comment by 100apps** [comment]
您的担忧很有道理。对您的打扰，我先表达歉意。

说一下我们团队的文化，我们团队多少有一些hacker气质，还记得《社交网络》中扎克伯格批量下载女同学照片的脚本吗？或许hacker只是觉得这样有意思、有用。我写这个脚本的时候其实并没有考虑很多，也没有考虑由此带来的法律问题，更没有考虑到您的愤怒。

请谅解。

**Comment by nimoc** [comment]
@100apps 请删除相关代码，我已经将 gmail 邮箱从 github 公开信息中撤掉了。
