### ISSUE TITLE
请停止这种群发邮件的行为

### ISSUE THREAD

**Issue by LearnShare** [100apps/IWantYou#7]
已经第二次收到邮件，不知道是不是特地运行了两遍，希望不再收到第三次。

首先，这是一种盲目的行为。就像单身青年站在地铁口，对每一位路过的女性问一句：愿意嫁给我吗？

然后，并没有什么诚意。几个特征值并不能说明这个人的技术栈，也说明不了技术水平，更无法判断这个人是否适合公司的职位。如此鲁莽地发邮件，可能得不到人才，甚至招来广泛的讨厌。

找老婆不是靠运气的，招人也不是。

**Comment by 100apps** [comment]
@LearnShare 第二封邮件不是我发的。
你可以看看发件人邮箱。有人clone了项目并且运行了。这个问题我已经fix了,见 #6

**Comment by LearnShare** [comment]
@100apps Got.
被滥用是无法避免了，所以不要写这些东西，弊大于利。
